// <auto-generated />
namespace Autorijschool3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class testrij : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testrij));
        
        string IMigrationMetadata.Id
        {
            get { return "201411271144534_testrij"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
